<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb80fba4c89c2fa0269156dd28e236d33
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Pakettikauppa\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Pakettikauppa\\' => 
        array (
            0 => __DIR__ . '/..' . '/pakettikauppa/api-library/src/Pakettikauppa',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb80fba4c89c2fa0269156dd28e236d33::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb80fba4c89c2fa0269156dd28e236d33::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
